'''@package AverageTemperatureData.py

Mapping of country names to their ISO ALPHA-2 and ISO ALPHA-3 codes. Contains
reverse mappings so countries can be reference by code and the name returned etc.

SOURCE: http://www.nationsonline.org/oneworld/country_code_list.htm)

Author: Ashok Fernandez
Date: 16/09/2013
'''

# Long written country name to ISO ALPHA-3 Code
NAME_TO_LONG_CODE = { 
	"Aruba" : "ABW",
	"Afghanistan" : "AFG",
	"Angola" : "AGO",
	"Anguilla" : "AIA",
	"Albania" : "ALB",
	"Andorra" : "AND",
	"United Arab Emirates" : "ARE",
	"Argentina" : "ARG",
	"Armenia" : "ARM",
	"American Samoa" : "ASM",
	"French Southern Territories" : "ATF",
	"Antigua and Barbuda" : "ATG",
	"Australia" : "AUS",
	"Austria" : "AUT",
	"Azerbaijan" : "AZE",
	"Burundi" : "BDI",
	"Belgium" : "BEL",
	"Benin" : "BEN",
	"Burkina Faso" : "BFA",
	"Bangladesh" : "BGD",
	"Bulgaria" : "BGR",
	"Bahrain" : "BHR",
	"Bahamas" : "BHS",
	"Bosnia and Herzegovina" : "BIH",
	"Belarus" : "BLR",
	"Belize" : "BLZ",
	"Bermuda" : "BMU",
	"Bolivia, Plurinational State of" : "BOL",
	"Brazil" : "BRA",
	"Barbados" : "BRB",
	"Brunei Darussalam" : "BRN",
	"Bhutan" : "BTN",
	"Botswana" : "BWA",
	"Central African Republic" : "CAF",
	"Canada" : "CAN",
	"Cocos (Keeling) Islands" : "CCK",
	"Switzerland" : "CHE",
	"Chile" : "CHL",
	"China" : "CHN",
	"Cote d'Ivoire" : "CIV",
	"Cameroon" : "CMR",
	"Congo, the Democratic Republic of the" : "COD",
	"Congo" : "COG",
	"Cook Islands" : "COK",
	"Colombia" : "COL",
	"Comoros" : "COM",
	"Cape Verde" : "CPV",
	"Costa Rica" : "CRI",
	"Cuba" : "CUB",
	"Christmas Island" : "CXR",
	"Cayman Islands" : "CYM",
	"Cyprus" : "CYP",
	"Czech Republic" : "CZE",
	"Germany" : "DEU",
	"Djibouti" : "DJI",
	"Dominica" : "DMA",
	"Denmark" : "DNK",
	"Dominican Republic" : "DOM",
	"Algeria" : "DZA",
	"Ecuador" : "ECU",
	"Egypt" : "EGY",
	"Eritrea" : "ERI",
	"Western Sahara" : "ESH",
	"Spain" : "ESP",
	"Estonia" : "EST",
	"Ethiopia" : "ETH",
	"Finland" : "FIN",
	"Fiji" : "FJI",
	"Falkland Islands (Malvinas)" : "FLK",
	"France" : "FRA",
	"Faroe Islands" : "FRO",
	"Micronesia, Federated States of" : "FSM",
	"Gabon" : "GAB",
	"United Kingdom" : "GBR",
	"Georgia" : "GEO",
	"Guernsey" : "GGY",
	"Ghana" : "GHA",
	"Gibraltar" : "GIB",
	"Guinea" : "GIN",
	"Guadeloupe" : "GLP",
	"Gambia" : "GMB",
	"Guinea-Bissau" : "GNB",
	"Equatorial Guinea" : "GNQ",
	"Greece" : "GRC",
	"Grenada" : "GRD",
	"Greenland" : "GRL",
	"Guatemala" : "GTM",
	"French Guiana" : "GUF",
	"Guam" : "GUM",
	"Guyana" : "GUY",
	"Hong Kong" : "HKG",
	"Honduras" : "HND",
	"Croatia" : "HRV",
	"Haiti" : "HTI",
	"Hungary" : "HUN",
	"Indonesia" : "IDN",
	"Isle of Man" : "IMN",
	"India" : "IND",
	"British Indian Ocean Territory" : "IOT",
	"Ireland" : "IRL",
	"Iran, Islamic Republic of" : "IRN",
	"Iraq" : "IRQ",
	"Iceland" : "ISL",
	"Israel" : "ISR",
	"Italy" : "ITA",
	"Jamaica" : "JAM",
	"Jersey" : "JEY",
	"Jordan" : "JOR",
	"Japan" : "JPN",
	"Kazakhstan" : "KAZ",
	"Kenya" : "KEN",
	"Kyrgyzstan" : "KGZ",
	"Cambodia" : "KHM",
	"Kiribati" : "KIR",
	"Saint Kitts and Nevis" : "KNA",
	"Korea, Republic of" : "KOR",
	"Kuwait" : "KWT",
	"Lao People's Democratic Republic" : "LAO",
	"Lebanon" : "LBN",
	"Liberia" : "LBR",
	"Libya" : "LBY",
	"Saint Lucia" : "LCA",
	"Liechtenstein" : "LIE",
	"Sri Lanka" : "LKA",
	"Lesotho" : "LSO",
	"Lithuania" : "LTU",
	"Luxembourg" : "LUX",
	"Latvia" : "LVA",
	"Macao" : "MAC",
	"Morocco" : "MAR",
	"Monaco" : "MCO",
	"Moldova, Republic of" : "MDA",
	"Madagascar" : "MDG",
	"Maldives" : "MDV",
	"Mexico" : "MEX",
	"Marshall Islands" : "MHL",
	"Macedonia, the former Yugoslav Republic of" : "MKD",
	"Mali" : "MLI",
	"Malta" : "MLT",
	"Myanmar" : "MMR",
	"Montenegro" : "MNE",
	"Mongolia" : "MNG",
	"Northern Mariana Islands" : "MNP",
	"Mozambique" : "MOZ",
	"Mauritania" : "MRT",
	"Montserrat" : "MSR",
	"Martinique" : "MTQ",
	"Mauritius" : "MUS",
	"Malawi" : "MWI",
	"Malaysia" : "MYS",
	"Mayotte" : "MYT",
	"Namibia" : "NAM",
	"New Caledonia" : "NCL",
	"Niger" : "NER",
	"Norfolk Island" : "NFK",
	"Nigeria" : "NGA",
	"Nicaragua" : "NIC",
	"Niue" : "NIU",
	"Netherlands" : "NLD",
	"Norway" : "NOR",
	"Nepal" : "NPL",
	"Nauru" : "NRU",
	"New Zealand" : "NZL",
	"Oman" : "OMN",
	"Pakistan" : "PAK",
	"Panama" : "PAN",
	"Pitcairn" : "PCN",
	"Peru" : "PER",
	"Philippines" : "PHL",
	"Palau" : "PLW",
	"Papua New Guinea" : "PNG",
	"Poland" : "POL",
	"Puerto Rico" : "PRI",
	"Korea, Democratic People's Republic of" : "PRK",
	"Portugal" : "PRT",
	"Paraguay" : "PRY",
	"Palestine, State of" : "PSE",
	"French Polynesia" : "PYF",
	"Qatar" : "QAT",
	"Reunion" : "REU",
	"Romania" : "ROU",
	"Russian Federation" : "RUS",
	"Rwanda" : "RWA",
	"Saudi Arabia" : "SAU",
	"Sudan" : "SDN",
	"Senegal" : "SEN",
	"Singapore" : "SGP",
	"Saint Helena, Ascension and Tristan da Cunha" : "SHN",
	"Svalbard and Jan Mayen" : "SJM",
	"Solomon Islands" : "SLB",
	"Sierra Leone" : "SLE",
	"El Salvador" : "SLV",
	"San Marino" : "SMR",
	"Somalia" : "SOM",
	"Serbia" : "SRB",
	"Sao Tome and Principe" : "STP",
	"Suriname" : "SUR",
	"Slovakia" : "SVK",
	"Slovenia" : "SVN",
	"Sweden" : "SWE",
	"Swaziland" : "SWZ",
	"Seychelles" : "SYC",
	"Syrian Arab Republic" : "SYR",
	"Turks and Caicos Islands" : "TCA",
	"Chad" : "TCD",
	"Togo" : "TGO",
	"Thailand" : "THA",
	"Tajikistan" : "TJK",
	"Tokelau" : "TKL",
	"Turkmenistan" : "TKM",
	"Timor-Leste" : "TLS",
	"Tonga" : "TON",
	"Trinidad and Tobago" : "TTO",
	"Tunisia" : "TUN",
	"Turkey" : "TUR",
	"Tuvalu" : "TUV",
	"Taiwan, Province of China" : "TWN",
	"Tanzania, United Republic of" : "TZA",
	"Uganda" : "UGA",
	"Ukraine" : "UKR",
	"United States Minor Outlying Islands" : "UMI",
	"Uruguay" : "URY",
	"United States" : "USA",
	"Uzbekistan" : "UZB",
	"Saint Vincent and the Grenadines" : "VCT",
	"Venezuela, Bolivarian Republic of" : "VEN",
	"Virgin Islands, British" : "VGB",
	"Virgin Islands, U.S." : "VIR",
	"Viet Nam" : "VNM",
	"Vanuatu" : "VUT",
	"Wallis and Futuna" : "WLF",
	"Samoa" : "WSM",
	"Yemen" : "YEM",
	"South Africa" : "ZAF",
	"Zambia" : "ZMB",
	"Zimbabwe" : "ZWE"}

# Swap the keys and values around so we can IS0 ALPHA-3 to name
LONG_CODE_TO_NAME = dict((value, key) for key, value in NAME_TO_LONG_CODE.iteritems())

# ISO ALPHA-2 to ISO ALPHA-3 codes
SHORT_CODE_TO_LONG_CODE = {
	"AL" : "ALB",
	"DZ" : "DZA",
	"AS" : "ASM",
	"AD" : "AND",
	"AO" : "AGO",
	"AI" : "AIA",
	"AG" : "ATG",
	"AR" : "ARG",
	"AM" : "ARM",
	"AW" : "ABW",
	"AU" : "AUS",
	"AT" : "AUT",
	"AZ" : "AZE",
	"BS" : "BHS",
	"BH" : "BHR",
	"BD" : "BGD",
	"BB" : "BRB",
	"BY" : "BLR",
	"BE" : "BEL",
	"BZ" : "BLZ",
	"BJ" : "BEN",
	"BM" : "BMU",
	"BT" : "BTN",
	"BO" : "BOL",
	"BA" : "BIH",
	"BW" : "BWA",
	"BR" : "BRA",
	"VG" : "VGB",
	"IO" : "IOT",
	"BN" : "BRN",
	"BG" : "BGR",
	"BF" : "BFA",
	"BI" : "BDI",
	"KH" : "KHM",
	"CM" : "CMR",
	"CA" : "CAN",
	"CV" : "CPV",
	"KY" : "CYM",
	"CF" : "CAF",
	"TD" : "TCD",
	"CL" : "CHL",
	"CN" : "CHN",
	"HK" : "HKG",
	"MO" : "MAC",
	"CX" : "CXR",
	"CC" : "CCK",
	"CO" : "COL",
	"KM" : "COM",
	"CG" : "COG",
	"CD" : "COD",
	"CK" : "COK",
	"CR" : "CRI",
	"CI" : "CIV",
	"HR" : "HRV",
	"CU" : "CUB",
	"CY" : "CYP",
	"CZ" : "CZE",
	"DK" : "DNK",
	"DJ" : "DJI",
	"DM" : "DMA",
	"DO" : "DOM",
	"EC" : "ECU",
	"EG" : "EGY",
	"SV" : "SLV",
	"GQ" : "GNQ",
	"ER" : "ERI",
	"EE" : "EST",
	"ET" : "ETH",
	"FK" : "FLK",
	"FO" : "FRO",
	"FJ" : "FJI",
	"FI" : "FIN",
	"FR" : "FRA",
	"GF" : "GUF",
	"PF" : "PYF",
	"TF" : "ATF",
	"GA" : "GAB",
	"GM" : "GMB",
	"GE" : "GEO",
	"DE" : "DEU",
	"GH" : "GHA",
	"GI" : "GIB",
	"GR" : "GRC",
	"GL" : "GRL",
	"GD" : "GRD",
	"GP" : "GLP",
	"GU" : "GUM",
	"GT" : "GTM",
	"GG" : "GGY",
	"GN" : "GIN",
	"GW" : "GNB",
	"GY" : "GUY",
	"HT" : "HTI",
	"HN" : "HND",
	"HU" : "HUN",
	"IS" : "ISL",
	"IN" : "IND",
	"ID" : "IDN",
	"IR" : "IRN",
	"IQ" : "IRQ",
	"IE" : "IRL",
	"IM" : "IMN",
	"IL" : "ISR",
	"IT" : "ITA",
	"JM" : "JAM",
	"JP" : "JPN",
	"JE" : "JEY",
	"JO" : "JOR",
	"KZ" : "KAZ",
	"KE" : "KEN",
	"KI" : "KIR",
	"KP" : "PRK",
	"KR" : "KOR",
	"KW" : "KWT",
	"KG" : "KGZ",
	"LA" : "LAO",
	"LV" : "LVA",
	"LB" : "LBN",
	"LS" : "LSO",
	"LR" : "LBR",
	"LY" : "LBY",
	"LI" : "LIE",
	"LT" : "LTU",
	"LU" : "LUX",
	"MK" : "MKD",
	"MG" : "MDG",
	"MW" : "MWI",
	"MY" : "MYS",
	"MV" : "MDV",
	"ML" : "MLI",
	"MT" : "MLT",
	"MH" : "MHL",
	"MQ" : "MTQ",
	"MR" : "MRT",
	"MU" : "MUS",
	"YT" : "MYT",
	"MX" : "MEX",
	"FM" : "FSM",
	"MD" : "MDA",
	"MC" : "MCO",
	"MN" : "MNG",
	"ME" : "MNE",
	"MS" : "MSR",
	"MA" : "MAR",
	"MZ" : "MOZ",
	"MM" : "MMR",
	"NA" : "NAM",
	"NR" : "NRU",
	"NP" : "NPL",
	"NL" : "NLD",
	"NC" : "NCL",
	"NZ" : "NZL",
	"NI" : "NIC",
	"NE" : "NER",
	"NG" : "NGA",
	"NU" : "NIU",
	"NF" : "NFK",
	"MP" : "MNP",
	"NO" : "NOR",
	"OM" : "OMN",
	"PK" : "PAK",
	"PW" : "PLW",
	"PS" : "PSE",
	"PA" : "PAN",
	"PG" : "PNG",
	"PY" : "PRY",
	"PE" : "PER",
	"PH" : "PHL",
	"PN" : "PCN",
	"PL" : "POL",
	"PT" : "PRT",
	"PR" : "PRI",
	"QA" : "QAT",
	"RE" : "REU",
	"RO" : "ROU",
	"RU" : "RUS",
	"RW" : "RWA",
	"SH" : "SHN",
	"KN" : "KNA",
	"LC" : "LCA",
	"VC" : "VCT",
	"WS" : "WSM",
	"SM" : "SMR",
	"ST" : "STP",
	"SA" : "SAU",
	"SN" : "SEN",
	"RS" : "SRB",
	"SC" : "SYC",
	"SL" : "SLE",
	"SG" : "SGP",
	"SK" : "SVK",
	"SI" : "SVN",
	"SB" : "SLB",
	"SO" : "SOM",
	"ZA" : "ZAF",
	"ES" : "ESP",
	"LK" : "LKA",
	"SD" : "SDN",
	"SR" : "SUR",
	"SJ" : "SJM",
	"SZ" : "SWZ",
	"SE" : "SWE",
	"CH" : "CHE",
	"SY" : "SYR",
	"TW" : "TWN",
	"TJ" : "TJK",
	"TZ" : "TZA",
	"TH" : "THA",
	"TL" : "TLS",
	"TG" : "TGO",
	"TK" : "TKL",
	"TO" : "TON",
	"TT" : "TTO",
	"TN" : "TUN",
	"TR" : "TUR",
	"TM" : "TKM",
	"TC" : "TCA",
	"TV" : "TUV",
	"UG" : "UGA",
	"UA" : "UKR",
	"AE" : "ARE",
	"GB" : "GBR",
	"US" : "USA",
	"UM" : "UMI",
	"UY" : "URY",
	"UZ" : "UZB",
	"VU" : "VUT",
	"VE" : "VEN",
	"VN" : "VNM",
	"VI" : "VIR",
	"WF" : "WLF",
	"EH" : "ESH",
	"YE" : "YEM",
	"ZM" : "ZMB",
	"ZW" : "ZWE"}
