"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../main.py']
DATA_FILES = ['../Resources/SolarFarmDiagram.bmp','../Resources/currencyList.txt','../Resources/help.html']
OPTIONS = {'argv_emulation': False}

setup(
	name="Solar Farm Calculator",
	version="v0.1",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
